#cloud-config
users:
- default
- name: mgrandi
  groups: admin
  shell: /bin/bash
  # disable password login
  lock_passwd: true
  sudo:
  - ALL=(ALL) NOPASSWD:ALL
  ssh-authorized-keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPcmMkSxD3/0fupXUdUXl4eQn+2WYB/fxoJHIpn5A4Wa
    snowyegret-s-1vcpu-1gb-sfo3-01_ed25519
chpasswd:
  list:
  - mgrandi:ilikegravy
  expire: false
package_update: true
package_upgrade: true
packages:
  - python3
  - python3-pip
  - python3-venv
  - python3-wheel
  - p7zip-full
  - build-essential
  - lua5.1
byobu_by_default: enable