- hosts: fascrape:azure_tag_type_fascrape
  roles:

    - artis3n.tailscale.machine
    - furaffinity_scrape
# humboldti already has tailscale installed manually
- hosts: humboldti
  roles:
    - furaffinity_scrape
